[package]
name = "simple-rust-websocket"
version = "0.1.0"
edition = "2021"
authors = ["Saad Moazzam"]

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"
futures-util = "0.3.31"